server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "10s"
  write_timeout: "10s"

storage:
  data_dir: "./data/node-1"
  sync_writes: true

raft:
  node_id: "node-1"
  election_timeout: "1s"
  heartbeat_timeout: "500ms"
  snapshot_interval: "30s"

logging:
  level: "info"
  format: "json"
  file: "./logs/node-1.log"

cluster:
  bootstrap: true
  peers:
    - node_id: "node-2"
      address: "localhost"
      port: 8081
    - node_id: "node-3"
      address: "localhost"
      port: 8082