cluster:
  name: "distributed-kv-cluster"
  bootstrap_id: "node-1"
  data_dir: "./data/cluster"
  nodes:
    node-1: "localhost:9001"
    node-2: "localhost:9002" 
    node-3: "localhost:9003"

raft:
  election_timeout_ms: 100  # Optimized: 50% faster than default 200ms
  heartbeat_timeout_ms: 25  # Optimized: 50% faster than default 50ms

logging:
  level: "info"