server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "10s"
  write_timeout: "10s"

storage:
  type: "database"  # Use PostgreSQL instead of file storage

database:
  host: "localhost"
  port: 5432
  database: "kvstore"
  username: "ajayalluri"
  password: ""
  ssl_mode: "prefer"
  max_conns: 10
  min_conns: 2
  max_conn_time: "1h"
  max_idle_time: "30m"

raft:
  node_id: "node-1"
  election_timeout: "1s"
  heartbeat_timeout: "500ms"
  snapshot_interval: "30s"

logging:
  level: "info"
  format: "json"
  file: ""

cluster:
  bootstrap: true
  peers: []